version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      
      - run:
          name: "Install project dependencies"
          command: nuget restore
      
      - run:
          name: "Run Build step"
          command: msbuild /p:Configuration=Release /p:DebugSymbols=false /p:TargetFrameworkVersion="v4.7"
          
      - run:
          name: "Run App step"
          command: .\bin\Release\testbuddy.exe